import { useEffect, useState, type FormEvent } from 'react'
import {
  useAdminAddAnswerOptionMutation, useAdminAddQuestionMutation, useAdminDeleteAnswerOptionMutation,
  useAdminDeleteQuestionMutation, useAdminGetAssessmentQuery, useAdminReorderAnswerOptionsMutation,
  useAdminReorderQuestionsMutation, useAdminUpdateAnswerOptionMutation, useAdminUpdateQuestionMutation,
} from '../api/adminCoursesApi'
import type { AnswerOptionAdminDto, QuestionAdminDto, QuestionType } from '../../../types/api'
import { ApiErrorNotice } from '../../learning-plans/components/LearnerUi'
import { FieldError, ReorderButtons } from './AdminAuthoring'
import { moveItem, sectionClass } from './adminAuthoringUtils'

const questionTypes: QuestionType[] = ['SingleChoice', 'MultipleChoice', 'TrueFalse']
const inputClass = 'rounded border px-3 py-2'

function AnswerOptions({ assessmentId, question, locked }: { assessmentId: string; question: QuestionAdminDto; locked: boolean }) {
  const [items, setItems] = useState<AnswerOptionAdminDto[]>([]), [editing, setEditing] = useState<string>()
  const [error, setError] = useState<unknown>()
  useEffect(() => setItems([...question.answerOptions].sort((a, b) => a.order - b.order)), [question.answerOptions])
  const [add, addState] = useAdminAddAnswerOptionMutation(), [update, updateState] = useAdminUpdateAnswerOptionMutation()
  const [remove] = useAdminDeleteAnswerOptionMutation(), [reorder, reorderState] = useAdminReorderAnswerOptionsMutation()
  const run = async (work: () => Promise<unknown>) => { setError(undefined); try { await work() } catch (caught) { setError(caught) } }
  const move = async (index: number, direction: -1 | 1) => { const previous = items, next = moveItem(items, index, direction); setItems(next); try { await reorder({ assessmentId, questionId: question.id, answerOptions: next.map((item, order) => ({ answerOptionId: item.id, order })) }).unwrap() } catch (caught) { setItems(previous); setError(caught) } }
  const save = async (event: FormEvent<HTMLFormElement>, option?: AnswerOptionAdminDto) => { event.preventDefault(); const form = event.currentTarget, data = new FormData(form), body = { text: String(data.get('text')), isCorrect: data.has('isCorrect'), order: option?.order ?? items.length }; await run(async () => { if (option) await update({ assessmentId, questionId: question.id, answerOptionId: option.id, ...body }).unwrap(); else await add({ assessmentId, questionId: question.id, ...body }).unwrap(); setEditing(undefined); form.reset() }) }
  const correctCount = items.filter(item => item.isCorrect).length
  return <div className="mt-3 border-l-2 border-gray-200 pl-4"><h4 className="font-semibold">Answer options</h4>
    {question.questionType === 'SingleChoice' && correctCount !== 1 && <p className="my-2 rounded bg-amber-50 p-2 text-xs text-amber-900">Single choice questions require exactly one correct answer. Currently: {correctCount}.</p>}
    {question.questionType === 'TrueFalse' && items.length !== 2 && <p className="my-2 text-xs text-amber-800">True/False questions require exactly two options.</p>}
    <div className="space-y-2">{items.map((option, index) => <div key={option.id} className="rounded bg-gray-50 p-3">
      {editing === option.id ? <form onSubmit={event => void save(event, option)} className="grid gap-2 sm:grid-cols-[1fr_auto_auto]"><label className="text-sm">Answer text<input autoFocus name="text" required defaultValue={option.text} onChange={() => setError(undefined)} className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Text"/></label><label className="self-center text-sm"><input name="isCorrect" type="checkbox" defaultChecked={option.isCorrect}/> Correct</label><div className="flex items-end gap-2"><button disabled={updateState.isLoading} className="rounded bg-blue-600 px-3 py-2 text-white">Save</button><button type="button" onClick={() => setEditing(undefined)} className="rounded border px-3 py-2">Cancel</button></div></form> : <div className="flex flex-wrap items-center gap-2"><span className="mr-auto">{index + 1}. {option.text} {option.isCorrect && <b className="text-emerald-700">(Correct)</b>}</span><ReorderButtons index={index} count={items.length} disabled={locked || reorderState.isLoading} onMove={direction => void move(index, direction)}/><button disabled={locked} onClick={() => setEditing(option.id)} className="text-blue-700">Edit</button><button disabled={locked} onClick={() => { if (confirm('Delete this answer option?')) void run(() => remove({ assessmentId, questionId: question.id, answerOptionId: option.id }).unwrap()) }} className="text-red-700">Delete</button></div>}
    </div>)}</div>
    {!locked && <form onSubmit={event => void save(event)} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><label className="text-sm">New answer<input name="text" required placeholder={question.questionType === 'TrueFalse' ? 'True or False' : 'Answer text'} className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Text"/></label><label className="self-center"><input name="isCorrect" type="checkbox"/> Correct</label><button disabled={addState.isLoading || (question.questionType === 'TrueFalse' && items.length >= 2)} className="self-end rounded bg-gray-800 px-3 py-2 text-white disabled:opacity-50">Add option</button></form>}
    {!!error && <div className="mt-2"><ApiErrorNotice error={error}/></div>}
  </div>
}

function QuestionCard({ assessmentId, question, index, count, locked, moving, onMove }: { assessmentId: string; question: QuestionAdminDto; index: number; count: number; locked: boolean; moving: boolean; onMove: (direction: -1 | 1) => void }) {
  const [editing, setEditing] = useState(false), [error, setError] = useState<unknown>(), [update, updateState] = useAdminUpdateQuestionMutation(), [remove] = useAdminDeleteQuestionMutation()
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setError(undefined); try { await update({ assessmentId, questionId: question.id, prompt: String(data.get('prompt')), questionType: String(data.get('questionType')) as QuestionType, points: Number(data.get('points')), order: Number(data.get('order')) }).unwrap(); setEditing(false) } catch (caught) { setError(caught) } }
  return <article className="rounded-lg border p-4">{editing ? <form onSubmit={save} className="grid gap-3 md:grid-cols-3"><label className="text-sm md:col-span-3">Prompt<textarea autoFocus name="prompt" required defaultValue={question.prompt} onChange={() => setError(undefined)} className={`mt-1 min-h-24 w-full ${inputClass}`}/><FieldError error={error} field="Prompt"/></label><label className="text-sm">Question type<select name="questionType" defaultValue={question.questionType} className={`mt-1 w-full ${inputClass}`}>{questionTypes.map(type => <option key={type}>{type}</option>)}</select><FieldError error={error} field="QuestionType"/></label><label className="text-sm">Points<input name="points" type="number" min="1" required defaultValue={question.points} className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Points"/></label><label className="text-sm">Order<input name="order" type="number" min="0" required defaultValue={question.order} className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Order"/></label><div className="flex gap-2 md:col-span-3"><button disabled={updateState.isLoading} className="rounded bg-blue-600 px-4 py-2 text-white">Save question</button><button type="button" onClick={() => setEditing(false)} className="rounded border px-4 py-2">Cancel</button></div>{!!error && <div className="md:col-span-3"><ApiErrorNotice error={error}/></div>}</form> : <><div className="flex flex-wrap items-start gap-3"><div className="mr-auto"><h3 className="font-semibold">{index + 1}. {question.prompt}</h3><p className="text-sm text-gray-600">{question.questionType} · {question.points} point{question.points === 1 ? '' : 's'}</p></div><ReorderButtons index={index} count={count} disabled={locked || moving} onMove={onMove}/><button disabled={locked} onClick={() => setEditing(true)} className="text-blue-700">Edit</button><button disabled={locked} onClick={() => { if (confirm('Delete this question and its answer options?')) void remove({ assessmentId, questionId: question.id }) }} className="text-red-700">Delete</button></div><AnswerOptions assessmentId={assessmentId} question={question} locked={locked}/></>}</article>
}

export function AssessmentAuthoring({ assessmentId, status }: { assessmentId: string; status: string }) {
  const query = useAdminGetAssessmentQuery(assessmentId), [items, setItems] = useState<QuestionAdminDto[]>([]), [error, setError] = useState<unknown>()
  useEffect(() => setItems([...(query.data?.questions ?? [])].sort((a, b) => a.order - b.order)), [query.data?.questions])
  const locked = status !== 'Draft', [add, addState] = useAdminAddQuestionMutation(), [reorder, reorderState] = useAdminReorderQuestionsMutation()
  const move = async (index: number, direction: -1 | 1) => { const previous = items, next = moveItem(items, index, direction); setItems(next); try { await reorder({ assessmentId, questions: next.map((item, order) => ({ questionId: item.id, order })) }).unwrap() } catch (caught) { setItems(previous); setError(caught) } }
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); setError(undefined); try { await add({ assessmentId, prompt: String(data.get('prompt')), questionType: String(data.get('questionType')) as QuestionType, points: Number(data.get('points')), order: items.length }).unwrap(); form.reset() } catch (caught) { setError(caught) } }
  return <section className={sectionClass}><h2 className="text-xl font-bold">Questions and answer key</h2><p className="text-sm text-gray-600">Correctness is available only in administrator contracts.</p>{locked && <p className="mt-3 rounded bg-amber-50 p-3 text-sm">Published and archived assessments are read-only.</p>}<div className="mt-4 space-y-4">{items.map((question, index) => <QuestionCard key={question.id} assessmentId={assessmentId} question={question} index={index} count={items.length} locked={locked} moving={reorderState.isLoading} onMove={direction => void move(index, direction)}/>)}</div>{!items.length && <p className="mt-4 rounded bg-gray-50 p-4">No questions yet.</p>}{!locked && <form onSubmit={create} className="mt-5 grid gap-3 rounded bg-gray-50 p-4 md:grid-cols-2"><label className="md:col-span-2">Prompt<textarea name="prompt" required className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Prompt"/></label><label>Question type<select name="questionType" className={`mt-1 w-full ${inputClass}`}>{questionTypes.map(type => <option key={type}>{type}</option>)}</select></label><label>Points<input name="points" type="number" min="1" defaultValue="1" required className={`mt-1 w-full ${inputClass}`}/><FieldError error={error} field="Points"/></label><button disabled={addState.isLoading} className="rounded bg-blue-600 px-4 py-2 text-white md:col-span-2">Add question</button></form>}{!!error && <div className="mt-3"><ApiErrorNotice error={error}/></div>}</section>
}
