import { Link } from 'react-router-dom'
import type { CareerPathwayDto, CareerReadinessDto } from '../../../types/api'
import type { CareerAuthoringProgress } from './adminAuthoringUtils'

export function SetupProgress({ status, progress }: { status: string; progress: CareerAuthoringProgress }) {
  const stages = [['Career Details', true], ['Career Skills', progress.hasSkills], ['Learning Pathway', progress.hasPathway], ['Pathway Levels', progress.hasLevels], ['Courses', progress.everyLevelHasCourse && progress.hasRequiredCourses], ['Course Content', false], ['Resources & Assessments', false], ['Review', progress.hasSkills && progress.hasPathway && progress.hasLevels && progress.everyLevelHasCourse], ['Publish', status === 'Published']] as const
  const next = stages.find(([, complete]) => !complete)?.[0]
  return <section className="mt-6 rounded-xl border bg-white p-5" aria-labelledby="authoring-progress"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 id="authoring-progress" className="text-xl font-bold">Authoring Progress</h2>{next && <p className="text-sm font-medium text-blue-700">Next: {next}</p>}</div><ol className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{stages.map(([label, complete], index) => <li key={label} className={`flex items-center gap-3 rounded-lg border p-3 text-sm ${complete ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full font-bold ${complete ? 'bg-emerald-700 text-white' : 'bg-white text-amber-800'}`}>{complete ? '✓' : index + 1}</span><span className="font-medium">{label}</span></li>)}</ol><p className="mt-3 text-xs text-gray-600">This is frontend authoring guidance only. Publication Readiness below is determined by the backend.</p></section>
}

function ReadinessAction({ entityType, entityId }: { entityType?: string | null; entityId?: string | null }) {
  if (!entityId || !entityType) return null
  switch (entityType.toLowerCase()) {
    case 'course': return <Link className="font-semibold text-blue-700" to={`/admin/courses/${entityId}`}>Open Course</Link>
    case 'skill': return <Link className="font-semibold text-blue-700" to={`/admin/skills/${entityId}`}>Open Skill</Link>
    case 'pathway': return <a className="font-semibold text-blue-700" href={`#pathway-${entityId}`}>Open Pathway</a>
    default: return null
  }
}

export function ReadinessChecklist({ readiness, loading, error: errorValue }: { readiness?: CareerReadinessDto; loading: boolean; error?: unknown }) {
  const error = Boolean(errorValue)
  return <aside id="career-readiness" className="mt-6 scroll-mt-6 rounded-xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-bold">Backend Readiness</h2>{readiness && <span className={`rounded-full px-3 py-1 text-xs font-bold ${readiness.isReady ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'}`}>{readiness.isReady ? 'Ready to Publish' : 'Curriculum Incomplete'}</span>}</div><p className="mt-1 text-sm text-gray-700">Publication readiness is authoritative from the backend.</p>{loading && <p className="mt-4 text-sm">Refreshing readiness…</p>}{error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-800">Readiness could not be loaded.</p>}<ul className="mt-4 grid gap-3">{readiness?.checks.map(check => <li key={check.code} className={`rounded-lg border p-3 ${check.passed ? 'border-emerald-200 bg-white' : check.blocking ? 'border-red-300 bg-red-50' : 'border-amber-300 bg-amber-50'}`}><div className="flex gap-2"><span aria-hidden="true" className={check.passed ? 'text-emerald-700' : check.blocking ? 'text-red-700' : 'text-amber-700'}>{check.passed ? '✓' : check.blocking ? '✕' : '○'}</span><div className="min-w-0 flex-1"><p className="font-medium">{check.label}</p>{check.message && <p className="mt-1 text-sm text-gray-700">{check.message}</p>}<div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><span>{check.blocking ? 'Blocking check' : 'Informational check'}</span>{!check.passed && <ReadinessAction entityType={check.entityType} entityId={check.entityId}/>}</div></div></div></li>)}</ul></aside>
}

export function PublicationSequence() {
  const steps = ['Publish the Career Category.', 'Publish Skills used by the Career and Courses.', 'Prepare Course dependencies: a required lesson, course skill, primary course skill, published prerequisites, and published external resources.', 'Publish Courses.', 'Assign Career Skills, with contiguous zero-based order and at least one required skill.', 'Create exactly one primary Pathway while the Career remains Draft.', 'Add Pathway Levels.', 'Add Course assignments.', 'Ensure zero-based contiguous level and course ordering.', 'Ensure at least one required Course.', 'Publish the primary Pathway while the Career is still Draft.', 'Refresh Career readiness.', 'Publish the Career.']
  return <details className="mt-6 rounded-xl border bg-white p-5"><summary className="cursor-pointer text-lg font-bold">Final publication sequence</summary><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm">{steps.map(step => <li key={step}>{step}</li>)}</ol></details>
}

export function AdminPathwayPreview({ pathway }: { pathway: CareerPathwayDto }) {
  return <section className="mt-5 rounded-xl border-2 border-dashed border-violet-400 bg-violet-50 p-5"><div className="rounded-lg bg-violet-700 px-4 py-2 text-center text-sm font-bold tracking-wide text-white">ADMIN PREVIEW — {pathway.status.toUpperCase()} CONTENT</div><div className="mt-4 flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-2xl font-bold">{pathway.name}</h3><p className="text-sm text-gray-600">Career Pathway v{pathway.version} · {pathway.status}</p></div>{pathway.isPrimary && <span className="rounded-full bg-violet-200 px-3 py-1 text-xs font-semibold">Primary Pathway</span>}</div>{pathway.levels.length === 0 && <p className="mt-5 rounded-lg bg-white p-4">This pathway has no curriculum levels yet.</p>}<div className="mt-5 space-y-5">{[...pathway.levels].sort((a,b) => a.order-b.order).map((level, levelIndex) => <section key={level.id} className="rounded-lg bg-white p-4 shadow-sm"><h4 className="text-lg font-bold">{levelIndex + 1}. {level.name}</h4>{level.description && <p className="mt-1 text-sm text-gray-600">{level.description}</p>}{level.courses.length === 0 ? <p className="mt-3 text-sm text-amber-800">No courses added — this level is incomplete.</p> : <ol className="mt-3 space-y-2">{[...level.courses].sort((a,b) => a.order-b.order).map(course => <li key={course.id} className="flex flex-wrap items-center gap-2"><span className="font-medium">{course.order + 1}. {course.courseTitle}</span><span className="rounded bg-gray-100 px-2 py-1 text-xs">{course.difficulty}</span><span className={`rounded px-2 py-1 text-xs ${course.isRequired ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-700'}`}>{course.isRequired ? 'Required' : 'Optional'}</span></li>)}</ol>}</section>)}</div></section>
}
