import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAdminAssignExternalResourceMutation } from '../api/adminCoursesApi'
import {
  useAdminCreateExternalResourceMutation, useAdminCreateInstructorMutation, useAdminCreateProviderMutation,
  useAdminGetInstructorsQuery, useAdminGetProvidersQuery,
} from '../api/adminProvidersApi'
import { ApiErrorNotice } from '../../learning-plans/components/LearnerUi'
import { SearchSelector } from './AdminAuthoring'
import { useDebounced } from './adminAuthoringUtils'
import type { ExternalResourceType, ResourceAccessType } from '../../../types/api'
import { normalizeExternalUrl } from './youtubeSearch'

const resourceTypes: ExternalResourceType[] = ['LectureVideo','VideoPlaylist','Reading','Exercise','ExternalAssessment','Assignment','AnswerGuide','CourseWebsite','CertificateOpportunity','Dataset','SoftwareTool','Other']
const accessTypes: ResourceAccessType[] = ['Free','FreeWithAccount','AuditFree','Paid','InstitutionRestricted','Unknown']
const fieldClass = 'mt-1 w-full rounded border px-3 py-2'

export function CourseResourceBuilder({ courseId, order, assignedUrls = [] }: { courseId: string; order: number; assignedUrls?: string[] }) {
  const [open, setOpen] = useState(false), [providerId, setProviderId] = useState(''), [instructorId, setInstructorId] = useState(''), [resourceId, setResourceId] = useState('')
  const [providerSearch, setProviderSearch] = useState(''), [instructorSearch, setInstructorSearch] = useState(''), [message, setMessage] = useState<string>(), [error, setError] = useState<unknown>()
  const providers = useAdminGetProvidersQuery({ page: 1, pageSize: 20, search: useDebounced(providerSearch) || undefined })
  const instructors = useAdminGetInstructorsQuery({ page: 1, pageSize: 20, search: useDebounced(instructorSearch) || undefined })
  const [createProvider, providerState] = useAdminCreateProviderMutation(), [createInstructor, instructorState] = useAdminCreateInstructorMutation()
  const [createResource, resourceState] = useAdminCreateExternalResourceMutation(), [assign, assignState] = useAdminAssignExternalResourceMutation()
  const createProviderSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); setError(undefined); try { const provider = await createProvider({ name: String(data.get('name')), slug: String(data.get('slug')), description: String(data.get('description')) || null, websiteUrl: String(data.get('websiteUrl')) || null, logoUrl: String(data.get('logoUrl')) || null }).unwrap(); setProviderId(provider.id); setMessage(`Provider “${provider.name}” created as Draft.`); form.reset() } catch (caught) { setError(caught) } }
  const createInstructorSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); setError(undefined); try { const instructor = await createInstructor({ learningProviderId: providerId, name: String(data.get('name')), title: String(data.get('title')) || null, biography: String(data.get('biography')) || null, profileUrl: String(data.get('profileUrl')) || null }).unwrap(); setInstructorId(instructor.id); setMessage(`Instructor “${instructor.name}” created as Draft.`); form.reset() } catch (caught) { setError(caught) } }
  const createResourceSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); setError(undefined); const url = String(data.get('url')); if (assignedUrls.some(existing => normalizeExternalUrl(existing) === normalizeExternalUrl(url))) { setMessage('That URL is already attached to this course. No duplicate resource was created.'); return } try { const resource = await createResource({ learningProviderId: providerId, instructorId: instructorId || null, title: String(data.get('title')), description: String(data.get('description')) || null, resourceType: String(data.get('resourceType')) as ExternalResourceType, accessType: String(data.get('accessType')) as ResourceAccessType, url, sourceLabel: String(data.get('sourceLabel')) || null, estimatedDurationMinutes: data.get('estimatedDurationMinutes') ? Number(data.get('estimatedDurationMinutes')) : null }).unwrap(); await assign({ courseId, externalLearningResourceId: resource.id, order, isRequired: data.has('isRequired'), notes: String(data.get('notes')) || null }).unwrap(); setResourceId(resource.id); setMessage(`External resource “${resource.title}” created and assigned. Review and publish its dependencies before publishing the course.`); form.reset() } catch (caught) { setError(caught) } }
  return <section className="mt-5 rounded-xl border border-indigo-200 bg-indigo-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Create attributed external resource</h3><p className="text-sm text-gray-700">External content remains the work of its provider or instructor. Careersity stores attribution and curriculum placement.</p></div><button type="button" onClick={() => setOpen(value => !value)} className="rounded border border-indigo-600 px-3 py-2 font-semibold text-indigo-700">{open ? 'Close resource builder' : 'Create Provider / Instructor / Resource'}</button></div>{open && <div className="mt-4 space-y-5">
    <div className="grid gap-4 lg:grid-cols-2"><div><SearchSelector label="Learning provider" value={providerId} onChange={setProviderId} onSearch={setProviderSearch} options={(providers.data?.items ?? []).map(provider => ({ id: provider.id, label: provider.name, description: provider.status }))} loading={providers.isFetching} error={providers.error}/></div><form onSubmit={createProviderSubmit} className="grid gap-2 rounded-lg border bg-white p-3 sm:grid-cols-2"><h4 className="font-semibold sm:col-span-2">Provider not found? Create Draft provider</h4><label>Name<input name="name" required className={fieldClass}/></label><label>Slug<input name="slug" required className={fieldClass}/></label><label className="sm:col-span-2">Description<textarea name="description" className={fieldClass}/></label><label>Website URL<input name="websiteUrl" type="url" className={fieldClass}/></label><label>Logo URL<input name="logoUrl" type="url" className={fieldClass}/></label><button disabled={providerState.isLoading} className="rounded bg-indigo-700 px-3 py-2 text-white sm:col-span-2">Create provider</button></form></div>
    <div className="grid gap-4 lg:grid-cols-2"><div><SearchSelector label="Instructor (optional)" value={instructorId} onChange={setInstructorId} onSearch={setInstructorSearch} options={(instructors.data?.items ?? []).filter(instructor => !providerId || instructor.learningProviderId === providerId).map(instructor => ({ id: instructor.id, label: instructor.name, description: instructor.providerName }))} loading={instructors.isFetching} error={instructors.error}/></div><form onSubmit={createInstructorSubmit} className="grid gap-2 rounded-lg border bg-white p-3 sm:grid-cols-2"><h4 className="font-semibold sm:col-span-2">Instructor not found? Create Draft instructor</h4><label>Name<input name="name" required className={fieldClass}/></label><label>Title<input name="title" className={fieldClass}/></label><label className="sm:col-span-2">Biography<textarea name="biography" className={fieldClass}/></label><label className="sm:col-span-2">Profile URL<input name="profileUrl" type="url" className={fieldClass}/></label><button disabled={!providerId || instructorState.isLoading} className="rounded bg-indigo-700 px-3 py-2 text-white sm:col-span-2 disabled:opacity-50">Create instructor for selected provider</button></form></div>
    <form onSubmit={createResourceSubmit} className="grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-2"><h4 className="font-semibold md:col-span-2">Create and assign external learning resource</h4><label>Resource title<input name="title" required className={fieldClass}/></label><label>Resource URL<input name="url" type="url" required className={fieldClass}/></label><label>Resource type<select name="resourceType" className={fieldClass}>{resourceTypes.map(value => <option key={value}>{value}</option>)}</select></label><label>Access type<select name="accessType" className={fieldClass}>{accessTypes.map(value => <option key={value}>{value}</option>)}</select></label><label className="md:col-span-2">Description<textarea name="description" className={fieldClass}/></label><label>Source label<input name="sourceLabel" placeholder="Provider's label or course name" className={fieldClass}/></label><label>Estimated duration (minutes)<input name="estimatedDurationMinutes" type="number" min="1" className={fieldClass}/></label><label className="md:col-span-2">Assignment notes<textarea name="notes" className={fieldClass}/></label><label><input name="isRequired" type="checkbox" defaultChecked/> Required for this course</label><button disabled={!providerId || resourceState.isLoading || assignState.isLoading} className="rounded bg-indigo-700 px-4 py-2 text-white disabled:opacity-50">Create and assign resource</button></form>
    {message && <div role="status" className="rounded bg-emerald-100 p-3 text-sm text-emerald-900"><p>{message}</p><div className="mt-2 flex flex-wrap gap-3">{providerId && <Link to={`/admin/providers/${providerId}`} className="font-semibold text-blue-700">Open provider →</Link>}{instructorId && <Link to={`/admin/instructors/${instructorId}`} className="font-semibold text-blue-700">Open instructor →</Link>}{resourceId && <Link to={`/admin/external-resources/${resourceId}`} className="font-semibold text-blue-700">Open external resource →</Link>}</div></div>}{!!error && <ApiErrorNotice error={error}/>}</div>}</section>
}
